### PR TITLE
Card #15: background of "x" changes to red on hover

### PR DESCRIPTION
**Pull request by mferrarini**
Test pull request

### CODE REVIEW

**Comment by mferrarini** [comment]
Test pull request

**Review by phil-plencner-hl — COMMENTED** [review]
I confirmed this is working as intended. Not sure this is something we actually want to merge in to the development branch? @enriquediaz: Can you confirm this design change is something we already decided?

**Comment by mferrarini** [comment]
[Test out pull request process, adding Enrique and Phil as reviewers](https://trello.com/c/yuX5i7JJ/100-test-out-pull-request-process-adding-enrique-and-phil-as-reviewers)

**Review by enriquediaz — APPROVED** [review]
I can confirm this design change was discussed and agreed upon. I just pulled down Maura's branch to my local dev (thanks @phil-plencner-hl!) and tried it out and the change looks great. Thanks, Maura! Approving the merge.

**Pull request merged**
